name: Build with Nuitka

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install websockets rich pypinyin pyyaml jieba markdown-it-py aiohttp
        pip install nuitka ordered-set zstandard
        
    - name: Build with Nuitka
      run: |
        python -m nuitka `
          --standalone `
          --onefile `
          --enable-plugin=anti-bloat `
          --windows-icon-from-ico=realme_sheep_triangle.ico `
          --assume-yes-for-downloads `
          --output-filename=echo-client.exe `
          --output-dir=dist `
          --remove-output `
          --company-name="Echo-Client" `
          --product-name="Echo Client" `
          --file-version="0.3.0" `
          --product-version="0.3.0" `
          --file-description="Echo-live WebSocket CLI Client" `
          --lto=yes `
          --jobs=2 `
          main.py
          
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: echo-client-windows-${{ github.sha }}
        path: dist/echo-client.exe
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/echo-client.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
